events {}

http {
    limit_req_zone $limit_key zone=unauth:10m rate=5r/s;

    map $remote_user $limit_key {
        default $binary_remote_addr;   # No valid user -> rate limit by IP
        ""      $binary_remote_addr;   # Explicit empty
        ~^.     "";                    # Any non-empty $remote_user -> skip limit
    }

server {
    server_name example.com;

    auth_basic           "Restricted Area";
    auth_basic_user_file /etc/nginx/.htpasswd;

    limit_req zone=unauth burst=10 nodelay;
    limit_req_status 429;

    location / {
      proxy_pass http://127.0.0.1:4090;
    }

    location /guacamole {
      proxy_pass http://127.0.0.1:8080/guacamole;
    }

    listen 80;
  }
}
