#!/usr/bin/env bash

set -euo pipefail

cleanup() {
  sudo docker rm -f guacamole;
  sudo docker rm -f guacd;

  pkill -f opencode
  pkill -f wayvnc;
  pkill -f chromium;

  hyprctl output remove Virtual-1
}

trap cleanup EXIT

sudo docker run \
  --add-host host.docker.internal:host-gateway \
  -p 4822:4822 \
  --name guacd \
  -d guacamole/guacd

sudo docker run --name guacamole \
  --add-host host.docker.internal:host-gateway \
  -e GUACD_HOSTNAME=host.docker.internal \
  -e LOG_LEVEL="debug" \
  -v "$(pwd)/guacamole:/etc/guacamole" \
  -d \
  -p 8080:8080 guacamole/guacamole

hyprctl output create headless Virtual-1

nohup wayvnc 0.0.0.0 5900 "Virtual-1" > wayvnc.out &

nohup chromium --user-data-dir="$(pwd)/chrome-profile" --remote-debugging-port=9222 > chromium.out &

nohup opencode web --hostname=0.0.0.0 > opencode.out &

sleep 2

CLIENTS=$(hyprctl clients -j | jq -r '.[] | select(.class | test("chromium"; "i")) | .address')

COUNT=$(echo "$CLIENTS" | wc -l)

echo "Found $COUNT Chromium window(s). Moving them to Virtual-1..."

for ADDR in $CLIENTS; do
    echo "→ Moving window $ADDR"
    hyprctl dispatch focuswindow address:"$ADDR" >/dev/null
    hyprctl dispatch movewindow mon:Virtual-1 >/dev/null
    sleep 0.2
done

hyprctl keyword monitor Virtual-1,preferred,auto,1

sleep infinity
